development:
  adapter: mysql2
  database: api_rails4_angularjs_development
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_general_ci
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  database: api_rails4_angularjs_test
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_general_ci
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
